version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: construction_punchlist_db
    environment:
      POSTGRES_DB: construction_punchlist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - punchlist_network

  redis:
    image: redis:7-alpine
    container_name: construction_punchlist_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - punchlist_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: construction_punchlist_backend
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: construction_punchlist
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    depends_on:
      - postgres
      - redis
    networks:
      - punchlist_network
    command: npm run dev

  web:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    container_name: construction_punchlist_web
    environment:
      VITE_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - ./web-app:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - punchlist_network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  punchlist_network:
    driver: bridge



